services:
  - type: web
    name: antares-manager
    env: python
    region: singapore
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      npm install --production --no-fund --no-audit
    startCommand: python main.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTO_EXE
        value: "1"
      - key: SILENT_CONFIG
        value: "1"
      - key: SILENT_SOCKET
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: NODE_VERSION
        value: "22"
